//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAIN
    {
        public int id { get; set; }
        public Nullable<int> first_server_id { get; set; }
        public Nullable<int> second_server_id { get; set; }
        public Nullable<int> third_server_id { get; set; }
    }
}
