//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONNECTION_SETTINGS
    {
        public int id { get; set; }
        public Nullable<int> connection_type { get; set; }
        public Nullable<int> count_of_servers { get; set; }
        public string server_name { get; set; }
    }
}
