//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER_INFO
    {
        public int id { get; set; }
        public string server_ip { get; set; }
        public Nullable<int> server_port { get; set; }
        public string server_name { get; set; }
    }
}
