//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
